### ISSUE TITLE
Need documentation on repo usage/process

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/sqlops-dataprotocolclient#73]
Would like to propose adding some documentation in Readme/Wiki about:
- What's the goal/requirements of this repository?
- When should one update the code in this repository?
- Who is the customer/end user of releases?
- Release timeline and how are releases validated.

**Comment by Charles-Gagnon** [comment]
FYI - some of that is already started here : https://github.com/microsoft/sqlops-dataprotocolclient/wiki/Releasing-Changes
